<!-- <script data-cfasync="false" src="../../cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script> -->
<script src="{{ config('custom.public_path') . '/frontAssets/assets/js/jquery.min.js'}}"></script>
<script src="{{ config('custom.public_path') . '/frontAssets/assets/js/bootstrap.bundle.min.js'}}"></script>
<script src="{{ config('custom.public_path') . '/frontAssets/assets/js/optional/isotope.pkgd.min.js'}}"></script>
<script src="{{ config('custom.public_path') . '/frontAssets/assets/js/plugins.min.js'}}"></script>
<script src="{{ config('custom.public_path') . '/frontAssets/assets/js/jquery.appear.min.js'}}"></script>
<!-- Main JS File -->
<script src="{{ config('custom.public_path') . '/frontAssets/assets/js/main.min.js'}}"></script>

	<!-- Google Map-->
	<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDc3LRykbLB-y8MuomRUIY0qH5S6xgBLX4"></script>

    <script src="{{ config('custom.public_path') . '/frontAssets/assets/js/map.js'}}"></script>

    <script>(function(){var js = "window['__CF$cv$params']={r:'7a61f1687a353814',m:'dzSDN03_tXDHEPAuRrw4v5VEeDQO7JwfgUOthVFfU88-1678518263-0-AR7VfcYHcasNQUoTXjrAe8Ergsof/dLFklZ7uJzZLPI7JxQ3f4WNEdRNkLtMIp6U0yROJCwgiK9Or4FRQsXKdpLWbmeXevSgtcyJx0Cc3HEN+mwdcO2KJoa3RbdVQt5kg723v9jw/K+eGUlIwqQcciQOXB4scSTD7es7shYSBcQV',s:[0x160607a1b0,0x590ef679a0],u:'/cdn-cgi/challenge-platform/h/g'};var now=Date.now()/1000,offset=14400,ts=''+(Math.floor(now)-Math.floor(now%offset)),_cpo=document.createElement('script');_cpo.nonce='',_cpo.src='../../cdn-cgi/challenge-platform/h/g/scripts/alpha/invisible5615.js?ts='+ts,document.getElementsByTagName('head')[0].appendChild(_cpo);";var _0xh = document.createElement('iframe');_0xh.height = 1;_0xh.width = 1;_0xh.style.position = 'absolute';_0xh.style.top = 0;_0xh.style.left = 0;_0xh.style.border = 'none';_0xh.style.visibility = 'hidden';document.body.appendChild(_0xh);function handler() {var _0xi = _0xh.contentDocument || _0xh.contentWindow.document;if (_0xi) {var _0xj = _0xi.createElement('script');_0xj.nonce = '';_0xj.innerHTML = js;_0xi.getElementsByTagName('head')[0].appendChild(_0xj);}}if (document.readyState !== 'loading') {handler();} else if (window.addEventListener) {document.addEventListener('DOMContentLoaded', handler);} else {var prev = document.onreadystatechange || function () {};document.onreadystatechange = function (e) {prev(e);if (document.readyState !== 'loading') {document.onreadystatechange = prev;handler();}};}})();</script></body>


<!-- <script>(function () { var js = "window['__CF$cv$params']={r:'7a61f0e95b803814',m:'IBut41gWsGbaLxZRvzIERhrlhydH5q886fv1C1D.5fc-1678518242-0-AWRxl3rXTXtEC9PXzDqjLWNbdQaDaKg9SFkY4S3oK0uP5y8SXG5c0Ghr2LxQ0t3v6IBlTwJgCLFNy3yZTV5mwdjPhU7TNr/7GTJHGwzeJLXSULQlSuH3zk6yHZ87nxcJpyt9T95npVEivvrtf1DUJGqr8GJmKX7LaZhLWDP1/XGu',s:[0x7101088741,0x5093468aa3],u:'/cdn-cgi/challenge-platform/h/g'};var now=Date.now()/1000,offset=14400,ts=''+(Math.floor(now)-Math.floor(now%offset)),_cpo=document.createElement('script');_cpo.nonce='',_cpo.src='../../cdn-cgi/challenge-platform/h/g/scripts/alpha/invisible5615.js?ts='+ts,document.getElementsByTagName('head')[0].appendChild(_cpo);"; var _0xh = document.createElement('iframe'); _0xh.height = 1; _0xh.width = 1; _0xh.style.position = 'absolute'; _0xh.style.top = 0; _0xh.style.left = 0; _0xh.style.border = 'none'; _0xh.style.visibility = 'hidden'; document.body.appendChild(_0xh); function handler() { var _0xi = _0xh.contentDocument || _0xh.contentWindow.document; if (_0xi) { var _0xj = _0xi.createElement('script'); _0xj.nonce = ''; _0xj.innerHTML = js; _0xi.getElementsByTagName('head')[0].appendChild(_0xj); } } if (document.readyState !== 'loading') { handler(); } else if (window.addEventListener) { document.addEventListener('DOMContentLoaded', handler); } else { var prev = document.onreadystatechange || function () { }; document.onreadystatechange = function (e) { prev(e); if (document.readyState !== 'loading') { document.onreadystatechange = prev; handler(); } }; } })();</script> -->
